<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>itsl2</AssemblyName>
    <RootNamespace>Itsl2.App</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Itsl2.Core\Itsl2.Core.csproj" />
    <ProjectReference Include="..\Itsl2.Game\Itsl2.Game.csproj" />
    <ProjectReference Include="..\Itsl2.Auth\Itsl2.Auth.csproj" />
    <ProjectReference Include="..\Itsl2.Download\Itsl2.Download.csproj" />
    <ProjectReference Include="..\Itsl2.Servers\Itsl2.Servers.csproj" />
  </ItemGroup>
</Project>